# Generated by Django 2.0.7 on 2021-04-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectricalTEBooks',
            new_name='CompsFEBooks',
        ),
        migrations.RenameModel(
            old_name='ElectricalSEBooks',
            new_name='CompsSEBooks',
        ),
        migrations.RenameModel(
            old_name='ElectricalFEBooks',
            new_name='CompsTEBooks',
        ),
        migrations.RenameModel(
            old_name='CivilSEBooks',
            new_name='EXTCFEBooks',
        ),
        migrations.RenameModel(
            old_name='CivilFEBooks',
            new_name='EXTCSEBooks',
        ),
        migrations.RenameModel(
            old_name='CivilTEBooks',
            new_name='EXTCTEBooks',
        ),
    ]
